apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: staging
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: changed
  secretRef:
    name: flux-system
  url: ssh://git@github.com/wprzechrzta/flux2-hub-spoke